spring.application.name=Springboot-API-REST

# 1. Configuración de la base de datos (SOPORTE PARA LOCAL Y AWS)
# Eliminamos 'spring.datasource.platform' porque ya no se usa en Spring Boot 3
# Usamos la sintaxis ${VAR:default} para que IntelliJ no explote si no hay variables
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT:localhost}:${DB_PORT:3306}/${DB_NAME:epn2_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:epn2_user}
spring.datasource.password=${DB_PASSWORD:epn2_password}

# 2. Configuración de Hibernate
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Swagger
springdoc.swagger-ui.path=/swagger-ui.html