name: Deploy Backend EPN2
on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push de Imágenes
        run: |
          # 1. Construir las imágenes
          # Como el docker-compose.yml tiene la propiedad 'image', 
          # las imágenes ya salen con el nombre de tu Docker Hub.
          docker compose build
          
          # 2. Subir directamente (ya tienen el nombre correcto según tu log)
          docker push ${{ secrets.DOCKER_USERNAME }}/epn2-ventas:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/epn2-despachos:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/epn2-db:latest

      - name: Desplegar en EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/epn2-backend
            cd ~/epn2-backend
            # Descargamos el compose de la rama deploy
            curl -L https://raw.githubusercontent.com/${{ github.repository }}/deploy/docker-compose.yml -o docker-compose.yml
            
            # Limpieza y despliegue
            docker compose down || true
            docker compose pull
            docker compose up -d